#include "mad/simulation/world.hpp"
#include "mad/common/types.hpp"
#include <cmath>
#include <limits>
#include <stdexcept>
namespace mad::simulation {
namespace { constexpr double kWheelbase=2.85; constexpr double kMaxSteering=0.45; constexpr double kMaxAccel=3.0; constexpr double kMaxBrake=-5.0; bool Overlap1D(double a0,double a1,double b0,double b1){ return !(a1 < b0 || b1 < a0);} bool AabbIntersects(const ActorState& a,const ActorState& b){ return Overlap1D(a.x-a.length*0.5,a.x+a.length*0.5,b.x-b.length*0.5,b.x+b.length*0.5) && Overlap1D(a.y-a.width*0.5,a.y+a.width*0.5,b.y-b.width*0.5,b.y+b.width*0.5);} }
TrafficBehavior TrafficBehaviorFromString(const std::string& text){ if(text=="cut_in_left") return TrafficBehavior::CutInLeft; if(text=="cut_in_right") return TrafficBehavior::CutInRight; if(text=="brake") return TrafficBehavior::Brake; return TrafficBehavior::Cruise; }
std::string ToString(TrafficBehavior behavior){ switch(behavior){ case TrafficBehavior::Cruise: return "cruise"; case TrafficBehavior::CutInLeft: return "cut_in_left"; case TrafficBehavior::CutInRight: return "cut_in_right"; case TrafficBehavior::Brake: return "brake"; } return "cruise"; }
World::World(mad::map::LaneMap lane_map): m_laneMap(std::move(lane_map)) {}
void World::Reset(const ScenarioDefinition& scenario){ m_snapshot={}; m_snapshot.sim_time=0.0; m_snapshot.ego=scenario.ego; m_snapshot.actors=scenario.actors; }
void World::Step(double dt, const ControlCommand& ego_command){ UpdateEgo(dt, ego_command); UpdateTraffic(dt); m_snapshot.sim_time += dt; }
void World::UpdateEgo(double dt, const ControlCommand& ego_command){ auto& ego = m_snapshot.ego; const double accel=mad::common::Clamp(ego_command.acceleration, kMaxBrake, kMaxAccel); const double steering=mad::common::Clamp(ego_command.steering_angle, -kMaxSteering, kMaxSteering); ego.speed=std::max(0.0, ego.speed + accel * dt); ego.yaw=mad::common::NormalizeAngle(ego.yaw + std::tan(steering)/kWheelbase*ego.speed*dt); ego.x += std::cos(ego.yaw)*ego.speed*dt; ego.y += std::sin(ego.yaw)*ego.speed*dt; ego.preferred_lane = m_laneMap.ClosestLane(ego.y); }
void World::UpdateTraffic(double dt){ for(auto& actor : m_snapshot.actors){ if(!actor.active) continue; UpdateTrafficBehavior(actor, dt); actor.x += actor.speed * dt; }}
void World::UpdateTrafficBehavior(ActorState& actor, double dt){ const double default_speed = actor.desired_speed > 0.0 ? actor.desired_speed : actor.speed; if(actor.behavior==TrafficBehavior::Brake && m_snapshot.ego.x >= actor.behavior_trigger_x){ actor.desired_speed = std::max(4.0, default_speed * 0.45); } if((actor.behavior==TrafficBehavior::CutInLeft || actor.behavior==TrafficBehavior::CutInRight) && m_snapshot.ego.x >= actor.behavior_trigger_x){ const int desired_lane = actor.behavior_target_lane >=0 ? actor.behavior_target_lane : (actor.behavior == TrafficBehavior::CutInLeft ? actor.preferred_lane - 1 : actor.preferred_lane + 1); if(m_laneMap.IsLaneValid(desired_lane)){ const double target_y=m_laneMap.LaneCenterY(desired_lane); const double dy=target_y-actor.y; const double step=mad::common::Clamp(dy, -actor.lane_change_rate*dt, actor.lane_change_rate*dt); actor.y += step; if(std::abs(target_y-actor.y) < 0.15){ actor.preferred_lane=desired_lane; actor.y=target_y; actor.behavior=TrafficBehavior::Cruise; } } } else { actor.y = m_laneMap.LaneCenterY(actor.preferred_lane); } const double target_speed = actor.desired_speed > 0.0 ? actor.desired_speed : default_speed; const double dv = target_speed - actor.speed; actor.speed = std::max(0.0, actor.speed + mad::common::Clamp(dv, -2.5 * dt, 1.2 * dt)); }
bool World::HasCollision() const { for(const auto& actor : m_snapshot.actors){ if(actor.active && AabbIntersects(m_snapshot.ego, actor)) return true; } return false; }
double World::DistanceToFrontActorInLane(int lane_id) const { const auto& ego = m_snapshot.ego; double best=std::numeric_limits<double>::infinity(); for(const auto& actor:m_snapshot.actors){ if(!actor.active || actor.preferred_lane != lane_id) continue; if(actor.x > ego.x) best = std::min(best, actor.x-ego.x-actor.length*0.5-ego.length*0.5); } return best; }
ScenarioDefinition MakeScenario(const std::string& scenario_name, const mad::map::LaneMap& lane_map){ ScenarioDefinition scenario; scenario.name=scenario_name; scenario.ego={1,mad::common::ActorType::Ego,0.0,lane_map.LaneCenterY(1),0.0,20.0,4.8,1.9,1,true};
 if(scenario_name=="highway_lane_change"){ scenario.actors={{101,mad::common::ActorType::Vehicle,35.0,lane_map.LaneCenterY(1),0.0,10.0,4.8,1.9,1,true},{102,mad::common::ActorType::Vehicle,20.0,lane_map.LaneCenterY(0),0.0,22.0,4.8,1.9,0,true},{103,mad::common::ActorType::Vehicle,90.0,lane_map.LaneCenterY(0),0.0,23.0,4.8,1.9,0,true},{104,mad::common::ActorType::Vehicle,65.0,lane_map.LaneCenterY(2),0.0,18.0,4.8,1.9,2,true}}; return scenario; }
 if(scenario_name=="dense_following"){ scenario.ego.speed=16.0; scenario.actors={{201,mad::common::ActorType::Vehicle,26.0,lane_map.LaneCenterY(1),0.0,12.0,4.8,1.9,1,true},{202,mad::common::ActorType::Vehicle,45.0,lane_map.LaneCenterY(0),0.0,14.0,4.8,1.9,0,true},{203,mad::common::ActorType::Vehicle,50.0,lane_map.LaneCenterY(2),0.0,13.0,4.8,1.9,2,true}}; return scenario; }
 if(scenario_name=="free_cruise"){ scenario.actors={{301,mad::common::ActorType::Vehicle,120.0,lane_map.LaneCenterY(0),0.0,22.0,4.8,1.9,0,true},{302,mad::common::ActorType::Vehicle,140.0,lane_map.LaneCenterY(2),0.0,22.0,4.8,1.9,2,true}}; return scenario; }
 if(scenario_name=="merge_pressure"){ scenario.ego.speed=20.0; scenario.actors={{401,mad::common::ActorType::Vehicle,24.0,lane_map.LaneCenterY(1),0.0,11.0,4.8,1.9,1,true},{402,mad::common::ActorType::Vehicle,10.0,lane_map.LaneCenterY(0),0.0,21.0,4.8,1.9,0,true},{403,mad::common::ActorType::Vehicle,55.0,lane_map.LaneCenterY(0),0.0,19.0,4.8,1.9,0,true},{404,mad::common::ActorType::Vehicle,35.0,lane_map.LaneCenterY(2),0.0,18.0,4.8,1.9,2,true}}; return scenario; }
 throw std::invalid_argument("Unknown scenario: " + scenario_name); }
}
